# Etapa 1: compila o projeto com Maven
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2: imagem final somente com o jar
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/target/os-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
